// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
function textResult(value, structured) {
  return {
    content: [{ type: "text", text: JSON.stringify(value) }],
    ...structured ? { structuredContent: structured } : {}
  };
}
function errorResult(message) {
  return {
    content: [{ type: "text", text: message }],
    isError: true
  };
}

// src/lib/mcp/tools/get-profile.ts
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get my profile",
  description: "Return the signed-in HarborForge user's profile information.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select("*").eq("id", ctx.getUserId()).maybeSingle();
    if (error) return errorResult(error.message);
    return textResult(data ?? { id: ctx.getUserId(), email: ctx.getUserEmail() });
  }
});

// src/lib/mcp/tools/get-balance.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_balance_default = defineTool2({
  name: "get_balance",
  title: "Get my balance",
  description: "Return the signed-in user's current HarborForge balance, computed from their transactions.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("transactions").select("amount, type").eq("user_id", ctx.getUserId());
    if (error) return errorResult(error.message);
    const balance = (data ?? []).reduce((sum, t) => {
      const amt = Number(t.amount) || 0;
      const isCredit = ["deposit", "roi", "referral", "credit"].includes(
        String(t.type ?? "").toLowerCase()
      );
      return sum + (isCredit ? amt : -Math.abs(amt));
    }, 0);
    return textResult({ balance, transaction_count: data?.length ?? 0 });
  }
});

// src/lib/mcp/tools/list-investment-plans.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
var list_investment_plans_default = defineTool3({
  name: "list_investment_plans",
  title: "List investment plans",
  description: "List all HarborForge investment plans available to invest in.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const { data, error } = await supabaseForUser(ctx).from("investment_plans").select("*").order("min_amount", { ascending: true });
    if (error) return errorResult(error.message);
    return textResult(data ?? []);
  }
});

// src/lib/mcp/tools/list-my-investments.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
var list_my_investments_default = defineTool4({
  name: "list_my_investments",
  title: "List my investments",
  description: "List the signed-in user's investments, optionally filtered by status.",
  inputSchema: {
    status: z.enum(["active", "completed", "cancelled"]).optional().describe("Optional status filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    let query = supabaseForUser(ctx).from("investments").select("*, investment_plans(name, roi_percentage, duration_days)").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false });
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return textResult(data ?? []);
  }
});

// src/lib/mcp/tools/list-my-deposits.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_my_deposits_default = defineTool5({
  name: "list_my_deposits",
  title: "List my deposits",
  description: "List the signed-in user's deposits, optionally filtered by status.",
  inputSchema: {
    status: z2.enum(["pending", "approved", "rejected"]).optional().describe("Optional status filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    let query = supabaseForUser(ctx).from("deposits").select("*").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false });
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return textResult(data ?? []);
  }
});

// src/lib/mcp/tools/list-my-withdrawals.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_my_withdrawals_default = defineTool6({
  name: "list_my_withdrawals",
  title: "List my withdrawals",
  description: "List the signed-in user's withdrawals, optionally filtered by status.",
  inputSchema: {
    status: z3.enum(["pending", "approved", "rejected"]).optional().describe("Optional status filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    let query = supabaseForUser(ctx).from("withdrawals").select("*").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false });
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return textResult(data ?? []);
  }
});

// src/lib/mcp/tools/list-my-transactions.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
var list_my_transactions_default = defineTool7({
  name: "list_my_transactions",
  title: "List my transactions",
  description: "List the signed-in user's transaction history, newest first.",
  inputSchema: {
    limit: z4.number().int().positive().optional().describe("Maximum number of transactions to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const { data, error } = await supabaseForUser(ctx).from("transactions").select("*").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(Math.min(limit ?? 50, 500));
    if (error) return errorResult(error.message);
    return textResult(data ?? []);
  }
});

// src/lib/mcp/index.ts
var projectRef = "wcygybphaulkaldhkrgw";
var mcp_default = defineMcp({
  name: "harborforge-mcp",
  title: "HarborForge",
  version: "0.1.0",
  instructions: "Tools for HarborForge investors. Read the signed-in user's profile, balance, deposits, withdrawals, investments, and transactions, and browse available investment plans.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_profile_default,
    get_balance_default,
    list_investment_plans_default,
    list_my_investments_default,
    list_my_deposits_default,
    list_my_withdrawals_default,
    list_my_transactions_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
